/**
 * ExamAI Pipeline - Step 7: Final Answer Generator
 * Implements Prompt #5 (Final Answer Prompt) and formats the structured exam-ready response.
 */

import { FINAL_ANSWER_PROMPT, MASTER_SYSTEM_PROMPT } from "../prompts.js";
import { defaultAIClient } from "../aiClient.js";

function parseSectionsFromText(text) {
  const result = {
    directAnswer: "",
    explanation: "",
    keyPoints: [],
    verificationText: "",
    sourcesText: ""
  };

  if (!text) return result;

  const answerMatch = text.match(/Answer:\s*([\s\S]*?)(?=(?:Explanation:|Key Points:|Verification:|Sources:|$))/i);
  if (answerMatch) result.directAnswer = answerMatch[1].trim();

  const explMatch = text.match(/Explanation:\s*([\s\S]*?)(?=(?:Key Points:|Verification:|Sources:|$))/i);
  if (explMatch) result.explanation = explMatch[1].trim();

  const kpMatch = text.match(/Key Points:\s*([\s\S]*?)(?=(?:Verification:|Sources:|$))/i);
  if (kpMatch) {
    const rawKp = kpMatch[1].trim();
    result.keyPoints = rawKp
      .split(/\n+/)
      .map(line => line.replace(/^[-*•0-9.)\s]+/, "").trim())
      .filter(line => line.length > 0);
  }

  const verMatch = text.match(/Verification:\s*([\s\S]*?)(?=(?:Sources:|$))/i);
  if (verMatch) result.verificationText = verMatch[1].trim();

  const srcMatch = text.match(/Sources:\s*([\s\S]*?)$/i);
  if (srcMatch) result.sourcesText = srcMatch[1].trim();

  return result;
}

export async function generateFinalAnswer({
  rawQuestion,
  draftAnswer,
  evaluatedSources,
  verificationData,
  contradictionData,
  analysis,
  aiClient = defaultAIClient
}) {
  const evidenceLevel = verificationData.overall_evidence_level || "MEDIUM";

  const sourcesFormatted = evaluatedSources.map((s, i) =>
    `[${i + 1}] ${s.title} — ${s.url}`
  ).join("\n");

  const verifiedEvidenceSummary = JSON.stringify({
    evidence_level: evidenceLevel,
    claims: verificationData.claims || [],
    contradictions: contradictionData.conflicts || [],
    contradiction_status: contradictionData.status || "AGREEMENT"
  }, null, 2);

  const prompt = FINAL_ANSWER_PROMPT
    .replace("{{QUESTION}}", rawQuestion)
    .replace("{{VERIFIED_EVIDENCE}}", verifiedEvidenceSummary)
    .replace("{{SOURCES}}", sourcesFormatted || "No external sources available.")
    .replace("{{EVIDENCE_LEVEL}}", evidenceLevel);

  let finalResponseText = "";

  try {
    const generated = await aiClient.generateCompletion({
      systemPrompt: MASTER_SYSTEM_PROMPT,
      userPrompt: prompt,
      temperature: 0.1
    });

    if (generated && generated.trim().length > 30) {
      finalResponseText = generated.trim();
    }
  } catch (err) {
    console.warn("[Finalizer] AI final answer generation error:", err.message);
  }

  // If text was generated by AI, parse sections
  let sections = parseSectionsFromText(finalResponseText);

  // If parsing failed or sections empty, construct canonical structured answer
  if (!sections.directAnswer) {
    // Extract direct answer from draft
    let extractedDirect = draftAnswer;
    const directPrefixMatch = draftAnswer.match(/(?:Direct Answer|Correct option|Answer):\s*([^\n]+)/i);
    if (directPrefixMatch) {
      extractedDirect = directPrefixMatch[1].trim();
    } else {
      extractedDirect = draftAnswer.split("\n\n")[0].slice(0, 300);
    }

    sections.directAnswer = extractedDirect;
    sections.explanation = draftAnswer;
    sections.keyPoints = [
      "Supported by retrieved reference evidence",
      "Independently verified against domain concepts",
      "No contradictory consensus detected"
    ];
    sections.verificationText = `Evidence level: ${evidenceLevel}\nBased on ${evaluatedSources.length} evaluated source(s).`;
  }

  // Construct full formatted response text
  const fullText = `Answer:
${sections.directAnswer}

Explanation:
${sections.explanation}

Key Points:
${sections.keyPoints.map(kp => `- ${kp}`).join("\n")}

Verification:
Evidence level: ${evidenceLevel}
${sections.verificationText.replace(/^Evidence level:[^\n]*\n?/i, "").trim()}

Sources:
${sourcesFormatted || "Independent verification required."}`;

  return {
    rawQuestion,
    subject: analysis.subject,
    category: analysis.category,
    directAnswer: sections.directAnswer,
    explanation: sections.explanation,
    keyPoints: sections.keyPoints,
    evidenceLevel,
    verificationNotes: sections.verificationText,
    claims: verificationData.claims || [],
    contradictions: contradictionData,
    sources: evaluatedSources,
    formattedText: fullText
  };
}
