import { test, beforeEach, afterEach } from "node:test";
import assert from "node:assert/strict";
import { analyzeQuestion } from "../pipeline/analyzer.js";
import { generateSearchQueries } from "../pipeline/queryGenerator.js";
import { deduplicateSources } from "../pipeline/search.js";
import { evaluateSources } from "../pipeline/evaluator.js";
import { detectContradictions, verifyEvidence } from "../pipeline/verifier.js";
import { runExamAIPipeline } from "../pipeline/orchestrator.js";
import { setupStandardMocks, teardownStandardMocks } from "./test-helpers.js";

beforeEach(() => {
  setupStandardMocks();
});

afterEach(() => {
  teardownStandardMocks();
});

test("Question Analyzer identifies MCQ questions", () => {
  const mcq = `What is the primary function of mitochondria?
A) Protein synthesis
B) ATP generation through cellular respiration
C) Lipid storage
D) DNA replication`;

  const analysis = analyzeQuestion(mcq);
  assert.equal(analysis.isMCQ, true);
  assert.equal(analysis.category, "multiple_choice");
  assert.equal(analysis.subject, "Biology");
  assert.equal(analysis.options.length, 4);
  assert.ok(analysis.options[1].includes("ATP generation"));
});

test("Question Analyzer identifies Mathematics questions", () => {
  const mathQ = "Calculate the derivative of f(x) = 3x^2 + 5x - 7 at x = 4.";
  const analysis = analyzeQuestion(mathQ);
  assert.equal(analysis.isMathematics, true);
  assert.equal(analysis.subject, "Mathematics");
});

test("Question Analyzer identifies Coding questions and language", () => {
  const codeQ = "Write a Python function to perform binary search on a sorted array.";
  const analysis = analyzeQuestion(codeQ);
  assert.equal(analysis.isCoding, true);
  assert.equal(analysis.programmingLanguage, "Python");
  assert.equal(analysis.subject, "Computer Science");
});

test("Query Generator produces 3-6 multi-angle queries", async () => {
  const analysis = analyzeQuestion("What causes the greenhouse effect?");
  const queries = await generateSearchQueries(analysis);
  assert.ok(Array.isArray(queries));
  assert.ok(queries.length >= 3, `Expected at least 3 queries, got ${queries.length}`);
  const types = queries.map(q => q.type);
  assert.ok(types.includes("exact") || types.includes("academic"));
});

test("Source Deduplication eliminates duplicate URLs and titles", () => {
  const mockSources = [
    { title: "Mitochondria Overview", url: "https://en.wikipedia.org/wiki/Mitochondria?utm_source=test", snippet: "Powerhouse of the cell." },
    { title: "Mitochondria Overview", url: "https://en.wikipedia.org/wiki/Mitochondria#history", snippet: "Organelle inside eukaryotes." },
    { title: "NCBI Cellular Respiration", url: "https://ncbi.nlm.nih.gov/books/NBK12345/", snippet: "ATP generation occurs in inner membrane." }
  ];

  const deduped = deduplicateSources(mockSources);
  assert.equal(deduped.length, 2, "Should deduplicate normalized URLs/titles");
  assert.equal(deduped[0].url, "https://en.wikipedia.org/wiki/Mitochondria");
});

test("Source Evaluator scores institutional and reference domains", async () => {
  const analysis = analyzeQuestion("Mitochondria function ATP");
  const sources = [
    { title: "NIH Mitochondria", url: "https://ncbi.nlm.nih.gov/cell", domain: "ncbi.nlm.nih.gov", snippet: "Mitochondria generate ATP." },
    { title: "Random Blog", url: "https://myblog.com/cells", domain: "myblog.com", snippet: "Cells are cool." }
  ];

  const evaluated = await evaluateSources(sources, analysis);
  assert.equal(evaluated.length, 2);
  assert.ok(evaluated[0].authority_score > evaluated[1].authority_score, "Institutional source should have higher authority");
  assert.equal(evaluated[0].quality, "HIGH");
});

test("Verifier detects source agreement and claim support", async () => {
  const sources = [
    { title: "Doc 1", url: "https://nih.gov", quality: "HIGH", snippet: "ATP is generated by ATP synthase in mitochondria." },
    { title: "Doc 2", url: "https://stanford.edu", quality: "HIGH", snippet: "Mitochondrial matrix and cristae synthesize ATP." }
  ];

  const contradictions = await detectContradictions("How do mitochondria make ATP?", sources);
  assert.equal(contradictions.status, "AGREEMENT");

  const verification = await verifyEvidence("How do mitochondria make ATP?", "Mitochondria synthesize ATP.", sources, contradictions);
  assert.equal(verification.overall_evidence_level, "HIGH");
  assert.ok(verification.claims.length > 0);
});

test("Complete 11-step Pipeline executes end-to-end", async () => {
  const question = "Which organelle generates the majority of ATP in eukaryotic cells?";
  const result = await runExamAIPipeline(question);

  assert.equal(result.success, true);
  assert.ok(result.directAnswer);
  assert.ok(result.explanation);
  assert.ok(result.keyPoints.length > 0);
  assert.ok(["HIGH", "MEDIUM", "LOW", "UNVERIFIED", "CONFLICTING"].includes(result.evidenceLevel));
  assert.ok(result.sources.length > 0);
  assert.ok(result.pipelineLog.length >= 6);
});

test("Pipeline handles Multiple-Choice questions", async () => {
  const mcq = `What is Newton's second law of motion?
A) F = ma
B) E = mc^2
C) V = IR
D) PV = nRT`;

  const result = await runExamAIPipeline(mcq);
  assert.equal(result.isMCQ, true);
  assert.equal(result.category, "multiple_choice");
  assert.equal(result.options.length, 4);
  assert.ok(result.directAnswer);
});

test("Pipeline handles Mathematics problems", async () => {
  const mathQ = "Calculate the integral of 2x dx from 0 to 3.";
  const result = await runExamAIPipeline(mathQ);
  assert.equal(result.category, "mathematics");
  assert.equal(result.subject, "Mathematics");
  assert.ok(result.directAnswer);
});

test("Pipeline handles Programming problems", async () => {
  const codeQ = "Write a Python function to check if a string is a palindrome.";
  const result = await runExamAIPipeline(codeQ);
  assert.equal(result.category, "coding");
  assert.equal(result.subject, "Computer Science");
  assert.ok(result.directAnswer);
});

test("Verifier assigns CONFLICTING when sources genuinely disagree", async () => {
  const conflictingSources = [
    { title: "Study A", url: "https://journal-a.org", quality: "HIGH", snippet: "Method X yields positive outcomes under all conditions." },
    { title: "Study B", url: "https://journal-b.org", quality: "HIGH", snippet: "Method X fails to produce positive outcomes in replicated trials." }
  ];

  const contradictionResult = {
    status: "CONFLICTING_EVIDENCE",
    agreement: [],
    conflicts: [{ claim: "Efficacy of Method X", source_a: 1, source_b: 2, discrepancy: "Contradictory clinical outcomes" }],
    explanation: "Replication studies disagree on the efficacy."
  };

  const verification = await verifyEvidence(
    "Is Method X effective?",
    "Method X is universally effective.",
    conflictingSources,
    contradictionResult
  );

  assert.equal(verification.overall_evidence_level, "CONFLICTING");
});

test("Verifier assigns UNVERIFIED when no sources are available", async () => {
  const contradictionResult = { status: "AGREEMENT", agreement: [], conflicts: [], explanation: "" };
  const verification = await verifyEvidence("Obscure unindexed question?", "Unverified answer.", [], contradictionResult);
  assert.equal(verification.overall_evidence_level, "UNVERIFIED");
});

